#
# Copyright (C) 2019 North Atlantics
#
# SPDX-License-Identifier:	GPL-2.0+
#

#nai
obj-$(CONFIG_NAI_COMMON) += nai_common.o
obj-$(CONFIG_NAI_MB) += nai_mb.o
obj-$(CONFIG_NAI_MISC) += nai_misc.o
obj-$(CONFIG_NAI_CPCI) += nai_pci.o
obj-$(CONFIG_NAI_VME) += nai_vme.o
obj-$(CONFIG_NAI_ICB) += nai_icb.o
obj-$(CONFIG_NAI_MODULE_SUPPORT) += nai_module_ext.o
obj-$(CONFIG_ID_EEPROM)	+= sys_eeprom.o
obj-$(CONFIG_NAI_ZYNQ_SLAVE) += master_slave.o

